export const api = [
    {
        id: 'Janeiro',
        entrada: '',
        ato_penitencial: '',
        gloria: '',
        proclamacao: '',
        ofertorio: '',
        santo: '',
        cordeiro: '',
        comunhao: '',
        acao_de_gracas: '',
        final: '',
    },
    {
        id: 'Fevereiro',
        entrada: '',
        ato_penitencial: '',
        gloria: '',
        proclamacao: '',
        ofertorio: '',
        santo: '',
        cordeiro: '',
        comunhao: '',
        acao_de_gracas: '',
        final: '',
    },
    {
        id: 'Março',
        entrada: '',
        ato_penitencial: '',
        gloria: '',
        proclamacao: '',
        ofertorio: '',
        santo: '',
        cordeiro: '',
        comunhao: '',
        acao_de_gracas: '',
        final: '',
    },
    {
        id: 'Abril',
        entrada: '',
        ato_penitencial: '',
        gloria: '',
        proclamacao: '',
        ofertorio: '',
        santo: '',
        cordeiro: '',
        comunhao: '',
        acao_de_gracas: '',
        final: '',
    },
    {
        id: 'Maio',
        entrada: '',
        ato_penitencial: '',
        gloria: '',
        proclamacao: '',
        ofertorio: '',
        santo: '',
        cordeiro: '',
        comunhao: '',
        acao_de_gracas: '',
        final: '',
    },
    {
        id: 'Junho',
        entrada: '',
        ato_penitencial: '',
        gloria: '',
        proclamacao: '',
        ofertorio: '',
        santo: '',
        cordeiro: '',
        comunhao: '',
        acao_de_gracas: '',
        final: '',
    },
    {
        id: 'Julho',
        entrada: '',
        ato_penitencial: '',
        gloria: '',
        proclamacao: '',
        ofertorio: '',
        santo: '',
        cordeiro: '',
        comunhao: '',
        acao_de_gracas: '',
        final: '',
    },
    {
        id: 'Agosto',
        entrada: '',
        ato_penitencial: '',
        gloria: '',
        proclamacao: '',
        ofertorio: '',
        santo: '',
        cordeiro: '',
        comunhao: '',
        acao_de_gracas: '',
        final: '',
    },
    {
        id: 'Setembro',
        entrada: '',
        ato_penitencial: '',
        gloria: '',
        proclamacao: '',
        ofertorio: '',
        santo: '',
        cordeiro: '',
        comunhao: '',
        acao_de_gracas: '',
        final: '',
    },
    {
        id: 'Outubro',
        entrada: '',
        ato_penitencial: '',
        gloria: '',
        proclamacao: '',
        ofertorio: '',
        santo: '',
        cordeiro: '',
        comunhao: '',
        acao_de_gracas: '',
        final: '',
    },
    {
        id: 'Novembro',
        entrada: '',
        ato_penitencial: '',
        gloria: '',
        proclamacao: '',
        ofertorio: '',
        santo: '',
        cordeiro: '',
        comunhao: '',
        acao_de_gracas: '',
        final: '',
    },
    {
        id: 'Dezembro',
        entrada: '',
        ato_penitencial: '',
        gloria: '',
        proclamacao: '',
        ofertorio: '',
        santo: '',
        cordeiro: '',
        comunhao: '',
        acao_de_gracas: '',
        final: '',
    }
]
